/* src/app/terms/page.js */
export default function TermsOfService() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '2rem', lineHeight: '1.6', color: 'var(--foreground)' }}>
      <h1 style={{fontSize: '2rem', marginBottom: '1rem'}}>Terms of Service</h1>
      <p style={{opacity: 0.6, marginBottom: '2rem'}}>Last updated: January 7, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using PromptVault (hosted at prompt-stash.xyz), you accept and agree to be bound by the terms and provision of this agreement.</p>

      <h2>2. "Local-First" Architecture & Data Liability</h2>
      <p>PromptVault operates on a "Local-First" basis. Your data is stored in your browser's local storage (IndexedDB). <strong>You are responsible for backing up your data</strong> (using the provided Export to JSON or Google Drive Sync features).</p>
      <p>We are not liable for data loss caused by clearing your browser cache, device failure, or accidental deletion.</p>

      <h2>3. Third-Party APIs</h2>
      <p>The application allows you to connect to third-party AI providers (OpenAI, Anthropic, Google Gemini, DeepSeek, etc.) using your own API keys. We are not responsible for:</p>
      <ul>
        <li>The availability or uptime of these third-party services.</li>
        <li>Costs incurred on your own API keys.</li>
        <li>The content generated by these AI models.</li>
      </ul>

      <h2>4. PRO License & Refunds</h2>
      <p>The PRO license unlocks advanced interface features (such as "Automator" mode and "Arena").</p>
      <p><strong>Refund Policy:</strong> Since the software offers a Free Trial (10 runs) to test functionality, and the license key is a digital non-returnable item, refunds are generally not provided unless the key is technically invalid.</p>

      <h2>5. User Conduct</h2>
      <p>You agree not to use the application to generate content that violates the usage policies of the connected AI providers (e.g., generating illegal or harmful content).</p>

      <h2>6. Contact & Support</h2>
      <p>For support, bug reports, or license issues, please contact: <strong>milligat13@gmail.com</strong></p>

      <div style={{marginTop: '2rem'}}>
        <a href="/" style={{color: 'var(--primary)', textDecoration: 'underline'}}>← Back to App</a>
      </div>
    </div>
  );
}